#!/bin/bash

power_on() {
    if bluetoothctl show | grep -q "Powered: yes"; then
        return 0
    else
        return 1
    fi
}

device_connected() {
    device_info=$(bluetoothctl info "$1")
    if echo "$device_info" | grep -q "Connected: yes"; then
        return 0
    else
        return 1
    fi
}


if power_on; then
    
    DEVICES=""
    counter=0
    # For Bash
    # mapfile -t paired_devices < <(bluetoothctl paired-devices | grep Device | cut -d ' ' -f 2) 
    # for device in "${paired_devices[@]}"; do
    paired_devices=$(bluetoothctl devices | grep Device | cut -d ' ' -f2)
    for device in $paired_devices
    do
        if device_connected $device; then
            device_alias=$(bluetoothctl info $device | grep "Alias" | cut -d ' ' -f 2-)
            #echo $device_alias
            if [ $counter -gt 0 ]; then
                DEVICES+=", ${device_alias}"
            else
                DEVICES+=" ${device_alias}"
            fi
            ((counter++))
        fi
    done
    [[ ! -z "$DEVICES" ]] &&  printf '^c#22BBFF^^d^'"$DEVICES"
fi

