#!/bin/bash

ufwstatus=$(sudo ufw status | awk 'NR==1{ print $2 }')

if [ "$ufwstatus" = "active" ]; then
       echo -e "^c#549665^ "
elif [ "$ufwstatus" = "inactive" ]; then
      echo -e "^c#d75f5f^ "
fi      


# edit sudoers to allow sudo access
# 1.open sudoers  
#
# sudo visudo
#
# 2.add below line
#
# Cmnd_Alias UFWSTATUS = /usr/sbin/ufw status
#
# 3.add below line at end of the file, before @includedir /etc/sudoers.d line 
#
# username ALL= NOPASSWD: UFWSTATUS
#
# username is your login name/user name (ALL = all the host)

# refer https://wiki.archlinux.org/title/sudo => Example entries => Note

# #a3e868  
# || xsetroot -name "^c#d3869b^[ $(mpd) ]  ^c#fabd2f^[ $(ram) ]  ^c#fb4934^[ $(vol) ]  ^c#83a598^[ $(wifi) ]  ^c#8ec07c^[ $(timedate) ] "
