#!/bin/bash

conntype=$(ip route | awk '/default/ { print substr($5,1,1) }')
if [ -z "$conntype" ]; then
       echo -e "^c#d75f5f^ ^d^"
elif [ "$conntype" = "e" ]; then
       echo -e "  "
elif [ "$conntype" = "w" ]; then
      echo -e ""
     # echo -e "^c#83A589^ ^d^"
fi      
